# config/packages/doctrine.yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            master:
                # configure these for your database server
                url: '%env(resolve:DATABASE_MASTER_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity\'
                        alias: Main
            master:
                connection: master
                mappings:
                    master:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Master'
                        prefix: 'App\Entity\Master'
                        alias: master
